### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by yvasileuski** [ylechelle/OpenIDFA#1]
For now there are:  armv7, armv7s, i386. Will you add arm64 support?

**Comment by ylechelle** [comment]
Yes, will be looking at that soon.
In the mean time, do you have any comment/reaction to this initiative?

**Comment by yvasileuski** [comment]
Thanks, this is very useful initiative to show Apple there are plenty of cool boys to fight with :-)

By the way, there is an open-source "fork" to demonstrate basic concept - https://github.com/mcorner/ActuallyOpenIDFA

**Comment by ylechelle** [comment]
Thanks ;-)
Yes, I’m in touch with Mark Corner. 
His project title is a bit tongue-in-cheek; and in fact has little to do with the algorithm I have implemented.
Additionally, his code, as is, is full of collision, much like web fingerprinting. Far from actuallyAnythingIDFA for now ;-)

**Comment by lisbakke** [comment]
What's the status on arm64 support?

**Comment by tibo** [comment]
since OpenIDFA is no longer a static library I'm pretty sure this issue is oudated

**Comment by lisbakke** [comment]
Ah. I'm using the cocoapod v0.1 Has that not been updated? It's complaining about arm64.

**Comment by ylechelle** [comment]
Hi Ben,
Indeed, Thibault is right. We have remove d the static lib (and the cocoa pod) recently, and instead have released the source code for 100% transparency. All you have to do is drag & drop the two files into your project.
Hope this helps,
Yann
