### ISSUE TITLE
OpenIDFA on CocoaPods needs to be updated for arm64

### ISSUE THREAD

**Issue by jonalmeida** [ylechelle/OpenIDFA#3]
In the 0.0.1 pod, the libOpenIDFA.a isn't built for 64bit devices. It might be best to expose the header and class files to the Pod so people can build their dependencies locally. This also benefits for those trying to build for iOS 6+ devices (32bit/64bit).

**Comment by jonalmeida** [comment]
For some reason the Podspec file has been removed. I'm not sure if that was intentional or not. Also is this still an active project?

**Comment by jonalmeida** [comment]
Worth mentioning that the reason this differs from #1 is because it would be easier to add OpenIDFA to static libraries via cocoapod.

UIApplication is also used, and static libraries don't add that in. Is there a way around it?

**Comment by ylechelle** [comment]
Hi John,
The static library has been removed. Meanwhile, the source code has been added…
Best,
Yann

**Comment by ylechelle** [comment]
Podspec has been removed for the same reason.

**Comment by jonalmeida** [comment]
@ylechelle Thanks for the update. It might be best to remove the Pod from the Cocoapods as well and not just the podspec file in this repository.

Also, I want to implement OpenIDFA into my static library, would I be able to remove the UIApplication dependency [here](https://github.com/jonalmeida/OpenIDFA/blob/master/OpenIDFA.m#L68)?

**Comment by ylechelle** [comment]
Indeed, need to look at the CocoaPods issue.
To implement OpenIDFA in your own static library, make sure to add a prefix of your own to the class… to avoid conflict.
Why would you want to remove the UIApplication dependency/method? It comes standard in UIKit… plus this part of the code is super important to make sure the OpenIDFA is very unique, and avoid unwanted collisions….

**Comment by jonalmeida** [comment]
Why not just add the two required headers into the class file though?

```
#import <UIKit/UIKit.h>
#import <UIKit/UIDevice.h>
```

UIKit.h for `[UIApplication sharedApplication]` and UIDevice for `[[UIDevice currentDevice] systemVersion]`.
