### ISSUE TITLE
iOS 9 SDK won't allow canOpenURL checks used in + (NSArray*) threeDaysOpenIDFAArray

### ISSUE THREAD

**Issue by peterbmarks** [ylechelle/OpenIDFA#6]
When we build under the iOS 9 SDK, the app spits out a series of:

2015-08-04 14:15:19.567 xxxxx[92223:11967607] -canOpenURL: failed for URL: "fb101015295179://" - error: "This app is not allowed to query for scheme fb101015295179"

While it's possible to allow certain url schemes, with an entry in Info.plist, we're going to need a long list.

As it stands I think this scheme won't work if we build on the iOS 9 SDK.

**Comment by ylechelle** [comment]
Hi Peter,

You are correct. Essentially, iOS9 will dramatically reduce the signature uniqueness by preventing generic calls to canOpenURL. A negative side effect is that it will increase collisions greatly, turning openIDFA into a potentially unreliable tracker.

At this point, I recommend shying away from openIDFA... doesn't look sustainable with recent evolutions.

Best,

Yann

**Comment by peterbmarks** [comment]
Thanks Yann.
